#ifndef INLCUIDOR_H
#define INLCUIDOR_H

#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <map>
#include <chrono>
#include <ctime>

class Atividade;
class Aula;
class Avaliacao;
class Disciplina;
class Docente;
class Estudante;
class Estudante;
class Estudo;
class Material;
class Periodo;
class Prova;
class Trabalho;
class LeitorAtividade;
class LeitorAvalicao;
class LeitorDisciplina;
class LeitorDisciplinaEstudante;
class LeitorDocente;
class LeitorEstudante;
class LeitorPeriodo;
class ControladorAtividade;
class ControladorAvalicao;
class ControladorDisciplina;
class ControladorDisciplinaEstudante;
class ControladorDocente;
class ControladorEstudante;
class ControladorPeriodo;

#include "Modelo/Atividade.h"
#include "Modelo/Aula.h"
#include "Modelo/Avaliacao.h"
#include "Modelo/Disciplina.h"
#include "Modelo/Docente.h"
#include "Modelo/Estudante.h"
#include "Modelo/Estudante.h"
#include "Modelo/Estudo.h"
#include "Modelo/Material.h"
#include "Modelo/Periodo.h"
#include "Modelo/Prova.h"
#include "Modelo/Trabalho.h"
#include "Leitor/LeitorAtividade.h"
#include "Leitor/LeitorAvaliacao.h"
#include "Leitor/LeitorDisciplina.h"
#include "Leitor/LeitorDisciplinaEstudante.h"
#include "Leitor/LeitorDocente.h"
#include "Leitor/LeitorEstudante.h"
#include "Leitor/LeitorPeriodo.h"
#include "Controlador/ControladorAtividade.h"
#include "Controlador/ControladorAvaliacao.h"
#include "Controlador/ControladorDisciplina.h"
#include "Controlador/ControladorDisciplinaEstudante.h"
#include "Controlador/ControladorDocente.h"
#include "Controlador/ControladorEstudante.h"
#include "Controlador/ControladorPeriodo.h"
#endif